
import { User, UserRole, PatientStatus, Language } from './types';

export const DOCTORS: User[] = [
  { id: 'doc1', name: 'Dr. Sarah Wilson', role: UserRole.DOCTOR },
  { id: 'doc2', name: 'Dr. Michael Chen', role: UserRole.DOCTOR },
  { id: 'doc3', name: 'Dr. Elena Rodriguez', role: UserRole.DOCTOR },
];

export const STATUS_COLORS: Record<PatientStatus, string> = {
  [PatientStatus.GOOD]: 'bg-green-100 text-green-800 border-green-200',
  [PatientStatus.STABLE]: 'bg-blue-100 text-blue-800 border-blue-200',
  [PatientStatus.SERIOUS]: 'bg-amber-100 text-amber-800 border-amber-200',
  [PatientStatus.CRITICAL]: 'bg-red-100 text-red-800 border-red-200',
};

export const STATUS_DOT_COLORS: Record<PatientStatus, string> = {
  [PatientStatus.GOOD]: 'bg-green-500',
  [PatientStatus.STABLE]: 'bg-blue-500',
  [PatientStatus.SERIOUS]: 'bg-amber-500',
  [PatientStatus.CRITICAL]: 'bg-red-500',
};

export const TRANSLATIONS: Record<Language, any> = {
  [Language.EN]: {
    loginTitle: 'MediQ Portal',
    loginSub: 'Please sign in to your account',
    patient: 'Patient',
    doctor: 'Doctor',
    fullName: 'Full Name',
    passcode: 'Passcode',
    staffProfile: 'Staff Profile',
    enterPortal: 'Enter Patient Portal',
    authenticate: 'Authenticate & Sign In',
    bookAppt: 'Book Appointment',
    myAppts: 'My Appointments',
    pharmacist: 'AI Pharmacist',
    symptoms: 'Symptoms',
    date: 'Date',
    time: 'Time',
    logout: 'Logout',
    report: 'Medicine Report',
    analyze: 'Analyze',
    totalPatients: 'Total Patients',
    seriousCases: 'Serious Cases',
    criticalCases: 'Critical Cases',
    patientQueue: 'Patient Queue',
    schedule: 'Schedule',
    triageStatus: 'Status',
    action: 'Action',
    review: 'Review',
    patientSymptoms: 'Symptoms Detail',
    updateTriage: 'Update Status',
    openChat: 'Open Chat',
    close: 'Close',
    noAppts: 'No appointments yet',
    healthTip: 'Health Tip',
    quickStats: 'Quick Stats',
    lastCheckup: 'Last Checkup',
    activePrescriptions: 'Active Prescriptions',
    secureConsultation: 'Secure Consultation',
    noMessages: 'No messages yet',
    typeMessage: 'Type your message...',
    uses: 'Uses',
    sideEffects: 'Side Effects',
    precautions: 'Precautions',
    alternatives: 'Alternatives',
    daysAgo: 'days ago'
  },
  [Language.HI]: {
    loginTitle: 'MediQ पोर्टल',
    loginSub: 'कृपया अपने खाते में साइन इन करें',
    patient: 'मरीज',
    doctor: 'डॉक्टर',
    fullName: 'पूरा नाम',
    passcode: 'पासकोड',
    staffProfile: 'स्टाफ प्रोफाइल',
    enterPortal: 'मरीज पोर्टल में प्रवेश करें',
    authenticate: 'प्रमाणित करें और साइन इन करें',
    bookAppt: 'अपॉइंटमेंट बुक करें',
    myAppts: 'मेरे अपॉइंटमेंट',
    pharmacist: 'एआई फार्मासिस्ट',
    symptoms: 'लक्षण',
    date: 'तारीख',
    time: 'समय',
    logout: 'लॉगआउट',
    report: 'दवा रिपोर्ट',
    analyze: 'विश्लेषण करें',
    totalPatients: 'कुल मरीज',
    seriousCases: 'गंभीर मामले',
    criticalCases: 'नाजुक मामले',
    patientQueue: 'मरीज की कतार',
    schedule: 'अनुसूची',
    triageStatus: 'स्थिति',
    action: 'कार्य',
    review: 'समीक्षा करें',
    patientSymptoms: 'लक्षण विवरण',
    updateTriage: 'स्थिति अपडेट करें',
    openChat: 'चैट खोलें',
    close: 'बंद करें',
    noAppts: 'अभी कोई अपॉइंटमेंट नहीं है',
    healthTip: 'स्वास्थ्य टिप',
    quickStats: 'त्वरित आँकड़े',
    lastCheckup: 'पिछली जांच',
    activePrescriptions: 'सक्रिय नुस्खे',
    secureConsultation: 'सुरक्षित परामर्श',
    noMessages: 'कोई संदेश नहीं',
    typeMessage: 'अपना संदेश लिखें...',
    uses: 'उपयोग',
    sideEffects: 'दुष्प्रभाव',
    precautions: 'सावधानियां',
    alternatives: 'विकल्प',
    daysAgo: 'दिन पहले'
  },
  [Language.MR]: {
    loginTitle: 'MediQ पोर्टल',
    loginSub: 'कृपया आपल्या खात्यात साइन इन करा',
    patient: 'रुग्ण',
    doctor: 'डॉक्टर',
    fullName: 'पूर्ण नाव',
    passcode: 'पासकोड',
    staffProfile: 'स्टाफ प्रोफाइल',
    enterPortal: 'रुग्ण पोर्टलमध्ये प्रवेश करा',
    authenticate: 'प्रमाणित करा आणि साइन इन करा',
    bookAppt: 'अपॉइंटमेंट बुक करा',
    myAppts: 'माझे अपॉइंटमेंट',
    pharmacist: 'एआई फार्मासिस्ट',
    symptoms: 'लक्षणे',
    date: 'तारीख',
    time: 'वेळ',
    logout: 'लॉगआउट',
    report: 'औषध अहवाल',
    analyze: 'विश्लेषण करा',
    totalPatients: 'एकूण रुग्ण',
    seriousCases: 'गंभीर केसेस',
    criticalCases: 'अति-गंभीर केसेस',
    patientQueue: 'रुग्णांची रांग',
    schedule: 'वेळापत्रक',
    triageStatus: 'स्थिती',
    action: 'कृती',
    review: 'तपासणी करा',
    patientSymptoms: 'लक्षणांचा तपशील',
    updateTriage: 'स्थिती बदला',
    openChat: 'चॅट सुरू करा',
    close: 'बंद करा',
    noAppts: 'अद्याप कोणतेही अपॉइंटमेंट नाही',
    healthTip: 'आरोग्य टिप्स',
    quickStats: 'त्वरित आकडेवारी',
    lastCheckup: 'शेवटची तपासणी',
    activePrescriptions: 'सक्रिय औषधे',
    secureConsultation: 'सुरक्षित सल्लामसलत',
    noMessages: 'अद्याप कोणतेही संदेश नाहीत',
    typeMessage: 'तुमचा संदेश टाइप करा...',
    uses: 'वापर',
    sideEffects: 'दुष्परिणाम',
    precautions: 'दक्षता',
    alternatives: 'पर्याय',
    daysAgo: 'दिवसांपूर्वी'
  },
  [Language.TA]: {
    loginTitle: 'MediQ போர்டல்',
    loginSub: 'உங்கள் கணக்கில் உள்நுழையவும்',
    patient: 'நோயாளி',
    doctor: 'மருத்துவர்',
    fullName: 'முழு பெயர்',
    passcode: 'கடவுக்குறியீடு',
    staffProfile: 'ஊழியர் விவரம்',
    enterPortal: 'நோயாளி போர்ட்டலில் நுழையவும்',
    authenticate: 'அங்கீகரித்து உள்நுழையவும்',
    bookAppt: 'சந்திப்பை பதிவு செய்யவும்',
    myAppts: 'என் சந்திப்புகள்',
    pharmacist: 'AI மருந்தாளர்',
    symptoms: 'அறிகுறிகள்',
    date: 'தேதி',
    time: 'நேரம்',
    logout: 'வெளியேறு',
    report: 'மருந்து அறிக்கை',
    analyze: 'ஆராயுங்கள்',
    totalPatients: 'மொத்த நோயாளிகள்',
    seriousCases: 'தீவிர வழக்குகள்',
    criticalCases: 'மிகவும் தீவிரமான வழக்குகள்',
    patientQueue: 'நோயாளி வரிசை',
    schedule: 'அட்டவணை',
    triageStatus: 'நிலை',
    action: 'செயல்',
    review: 'மதிப்பாய்வு',
    patientSymptoms: 'அறிகுறிகளின் விவரம்',
    updateTriage: 'நிலையைப் புதுப்பிக்கவும்',
    openChat: 'அரட்டையைத் திறக்கவும்',
    close: 'மூடு',
    noAppts: 'இன்னும் சந்திப்புகள் இல்லை',
    healthTip: 'ஆரோக்கிய குறிப்பு',
    quickStats: 'புள்ளிவிவரங்கள்',
    lastCheckup: 'கடைசி பரிசோதனை',
    activePrescriptions: 'செயலில் உள்ள மருந்துகள்',
    secureConsultation: 'பாதுகாப்பான ஆலோசனை',
    noMessages: 'இன்னும் செய்திகள் இல்லை',
    typeMessage: 'உங்கள் செய்தியை தட்டச்சு செய்க...',
    uses: 'பயன்கள்',
    sideEffects: 'பக்க விளைவுகள்',
    precautions: 'தற்காப்பு நடவடிக்கைகள்',
    alternatives: 'மாற்றுகள்',
    daysAgo: 'நாட்களுக்கு முன்பு'
  }
};
